Rename Entry.filter to .filter_with due to conflict with ActiveRecord::Relation
> ArgumentError: You tried to define a scope named "filter" on the model
> "Entry", but ActiveRecord::Relation already defined an instance method
> with the same name.